#!/bin/sh

here=`dirname $0`
if [ $here = '.' ]
then
   here=`pwd`
fi

# Appends lines from $1 to $2 if they are missing (if strcmp fails)
appendIfMissing() {
   if [ ! -f $2 ];
   then
      echo "$1" > $2
   else
      echo "$1" | while read -r line; do
         if grep -Fxq "$line" "$2"
         then
            echo "No need to update $2 with $line."
         else
            echo $line >> $2
         fi
      done # < $1
   fi
}

appendIfMissing ". $here/.bashrc"           ~/.bashrc
appendIfMissing '(load "'$here'/.emacs")'   ~/.emacs
appendIfMissing "source $here/.vimrc"       ~/.vimrc
appendIfMissing "source('$here/.Renviron')" ~/.Renviron
appendIfMissing "`cat $here/ssh-config`"    ~/.ssh/config
